name: "phishurl-appshield-combined-lstm-dnn-onnx"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 1024
default_model_filename: "url_model.onnx"

input [
{
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ 500 ]
},
{
    name: "input_2"
    data_type: TYPE_FP32
    dims: [ 17 ]
}
]
output [
{
    name: "dense_1"
    data_type: TYPE_FP32
    dims: [ 1 ]
}
]

dynamic_batching {
preferred_batch_size: [ 1, 4, 8, 12, 16, 32 ]
max_queue_delay_microseconds: 50000
}

optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }
    parameters { key: "max_workspace_size_bytes" value: "1073741824" }
    }]
}}

parameters [
  {
    key: "model_type"
    value: { string_value: "lstm-dnn" }
  },
  {
    key: "predict_proba"
    value: { string_value: "true" }
  },
  {
    key: "output_class"
    value: { string_value: "true" }
  },
  {
    key: "threshold"
    value: { string_value: "0.77" }
  },
  {
    key: "algo"
    value: { string_value: "ALGO_AUTO" }
  },
  {
    key: "storage_type"
    value: { string_value: "AUTO" }
  },
  {
    key: "blocks_per_sm"
    value: { string_value: "0" }
  }
]

